Add validation annotation for SendHabitNotification and sendHabitNoti…
GreenCityProject/GreenCityUser21_team_1_October pull request #4
Opened 2024-10-30 18:18 UTC by DmytroKaplun

…fication() method parameter

2024-10-30 19:31 UTC, SezamUA requested changes
You mistakaly set validation to name field instead of email field:

@Email(message = "Invalid email format")
    private String name;
    private String email;

2024-10-30 23:06 UTC, SezamUA approved these changes

2024-10-31 16:48 UTC, StannyB9 approved these changes

2024-11-02 14:13 UTC, maks741 approved these changes

2024-11-02 16:27 UTC, merged